//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 03:16:55 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ddit.or.kr", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package zero26_schema.generate;
