//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 03:16:55 PM KST 
//


package zero26_schema.generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="resource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="settings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="cacheModelsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;attribute name="enhancementEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;attribute name="lazyLoadingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;attribute name="maxRequests" type="{http://www.w3.org/2001/XMLSchema}int" default="32" />
 *                 &lt;attribute name="maxSessions" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
 *                 &lt;attribute name="maxTransactions" use="required" type="{http://www.w3.org/2001/XMLSchema}int" fixed="5" />
 *                 &lt;attribute name="useStatementNamespaces" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transactionManager">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataSource">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="property">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" default="SIMPLE" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sqlMap">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="namespace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties",
    "settings",
    "transactionManager",
    "sqlMap"
})
@XmlRootElement(name = "sqlMapConfig")
public class SqlMapConfig {

    protected SqlMapConfig.Properties properties;
    @XmlElement(required = true)
    protected SqlMapConfig.Settings settings;
    @XmlElement(required = true)
    protected SqlMapConfig.TransactionManager transactionManager;
    @XmlElement(required = true)
    protected SqlMapConfig.SqlMap sqlMap;
    @XmlAttribute(name = "namespace", required = true)
    protected String namespace;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link SqlMapConfig.Properties }
     *     
     */
    public SqlMapConfig.Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlMapConfig.Properties }
     *     
     */
    public void setProperties(SqlMapConfig.Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link SqlMapConfig.Settings }
     *     
     */
    public SqlMapConfig.Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlMapConfig.Settings }
     *     
     */
    public void setSettings(SqlMapConfig.Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the transactionManager property.
     * 
     * @return
     *     possible object is
     *     {@link SqlMapConfig.TransactionManager }
     *     
     */
    public SqlMapConfig.TransactionManager getTransactionManager() {
        return transactionManager;
    }

    /**
     * Sets the value of the transactionManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlMapConfig.TransactionManager }
     *     
     */
    public void setTransactionManager(SqlMapConfig.TransactionManager value) {
        this.transactionManager = value;
    }

    /**
     * Gets the value of the sqlMap property.
     * 
     * @return
     *     possible object is
     *     {@link SqlMapConfig.SqlMap }
     *     
     */
    public SqlMapConfig.SqlMap getSqlMap() {
        return sqlMap;
    }

    /**
     * Sets the value of the sqlMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlMapConfig.SqlMap }
     *     
     */
    public void setSqlMap(SqlMapConfig.SqlMap value) {
        this.sqlMap = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="resource" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Properties {

        @XmlAttribute(name = "resource")
        protected String resource;

        /**
         * Gets the value of the resource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResource() {
            return resource;
        }

        /**
         * Sets the value of the resource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResource(String value) {
            this.resource = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="cacheModelsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="enhancementEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="lazyLoadingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="maxRequests" type="{http://www.w3.org/2001/XMLSchema}int" default="32" />
     *       &lt;attribute name="maxSessions" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
     *       &lt;attribute name="maxTransactions" use="required" type="{http://www.w3.org/2001/XMLSchema}int" fixed="5" />
     *       &lt;attribute name="useStatementNamespaces" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Settings {

        @XmlAttribute(name = "cacheModelsEnabled")
        protected Boolean cacheModelsEnabled;
        @XmlAttribute(name = "enhancementEnabled")
        protected Boolean enhancementEnabled;
        @XmlAttribute(name = "lazyLoadingEnabled")
        protected Boolean lazyLoadingEnabled;
        @XmlAttribute(name = "maxRequests")
        protected Integer maxRequests;
        @XmlAttribute(name = "maxSessions")
        protected Integer maxSessions;
        @XmlAttribute(name = "maxTransactions", required = true)
        protected int maxTransactions;
        @XmlAttribute(name = "useStatementNamespaces", required = true)
        protected boolean useStatementNamespaces;

        /**
         * Gets the value of the cacheModelsEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCacheModelsEnabled() {
            if (cacheModelsEnabled == null) {
                return true;
            } else {
                return cacheModelsEnabled;
            }
        }

        /**
         * Sets the value of the cacheModelsEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCacheModelsEnabled(Boolean value) {
            this.cacheModelsEnabled = value;
        }

        /**
         * Gets the value of the enhancementEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isEnhancementEnabled() {
            if (enhancementEnabled == null) {
                return true;
            } else {
                return enhancementEnabled;
            }
        }

        /**
         * Sets the value of the enhancementEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEnhancementEnabled(Boolean value) {
            this.enhancementEnabled = value;
        }

        /**
         * Gets the value of the lazyLoadingEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isLazyLoadingEnabled() {
            if (lazyLoadingEnabled == null) {
                return true;
            } else {
                return lazyLoadingEnabled;
            }
        }

        /**
         * Sets the value of the lazyLoadingEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLazyLoadingEnabled(Boolean value) {
            this.lazyLoadingEnabled = value;
        }

        /**
         * Gets the value of the maxRequests property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getMaxRequests() {
            if (maxRequests == null) {
                return  32;
            } else {
                return maxRequests;
            }
        }

        /**
         * Sets the value of the maxRequests property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMaxRequests(Integer value) {
            this.maxRequests = value;
        }

        /**
         * Gets the value of the maxSessions property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getMaxSessions() {
            if (maxSessions == null) {
                return  10;
            } else {
                return maxSessions;
            }
        }

        /**
         * Sets the value of the maxSessions property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMaxSessions(Integer value) {
            this.maxSessions = value;
        }

        /**
         * Gets the value of the maxTransactions property.
         * 
         */
        public int getMaxTransactions() {
            return maxTransactions;
        }

        /**
         * Sets the value of the maxTransactions property.
         * 
         */
        public void setMaxTransactions(int value) {
            this.maxTransactions = value;
        }

        /**
         * Gets the value of the useStatementNamespaces property.
         * 
         */
        public boolean isUseStatementNamespaces() {
            return useStatementNamespaces;
        }

        /**
         * Sets the value of the useStatementNamespaces property.
         * 
         */
        public void setUseStatementNamespaces(boolean value) {
            this.useStatementNamespaces = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="resource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SqlMap {

        @XmlAttribute(name = "resource", required = true)
        protected String resource;

        /**
         * Gets the value of the resource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResource() {
            return resource;
        }

        /**
         * Sets the value of the resource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResource(String value) {
            this.resource = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataSource">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="property">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" default="SIMPLE" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSource"
    })
    public static class TransactionManager {

        @XmlElement(required = true)
        protected SqlMapConfig.TransactionManager.DataSource dataSource;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the dataSource property.
         * 
         * @return
         *     possible object is
         *     {@link SqlMapConfig.TransactionManager.DataSource }
         *     
         */
        public SqlMapConfig.TransactionManager.DataSource getDataSource() {
            return dataSource;
        }

        /**
         * Sets the value of the dataSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link SqlMapConfig.TransactionManager.DataSource }
         *     
         */
        public void setDataSource(SqlMapConfig.TransactionManager.DataSource value) {
            this.dataSource = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="property">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" default="SIMPLE" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "property"
        })
        public static class DataSource {

            @XmlElement(required = true)
            protected List<SqlMapConfig.TransactionManager.DataSource.Property> property;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the property property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the property property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SqlMapConfig.TransactionManager.DataSource.Property }
             * 
             * 
             */
            public List<SqlMapConfig.TransactionManager.DataSource.Property> getProperty() {
                if (property == null) {
                    property = new ArrayList<SqlMapConfig.TransactionManager.DataSource.Property>();
                }
                return this.property;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                if (type == null) {
                    return "SIMPLE";
                } else {
                    return type;
                }
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Property {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "value", required = true)
                protected String value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }

}
